### ISSUE TITLE
Cannot use "lex:LocXXXX KEYNAME" without Key=

### ISSUE THREAD

**Issue by godfetish** [SeriousM/WPFLocalizationExtension#88] opened 2016-01-29 20:52 UTC
I had to pull an old release of our HMI to make some custom modifications, I am using VS2015 (instead of VS2013 like the original developer) and I got the project to compile just fine in December.  I did not go into testing or even opening a Design window, though I did look at some classes to see where I needed to add some PLC tags - the test was to compile an installer and see no errors and it passed. I even installed the app packaged by InstallShield onto my laptop and it runs fine. Well, this week I had time to jump back into it and started getting this error below and am unable to use the Design View. I think the only change was updating VS2015 to Update 1...but I couldn't swear that it wasn't happening before either =/

I can compile with or without the Key= notation, btw. The files work without any issues. It's just preventing the XAML from showing in the Design View until I fix all of the localization. Since all I am doing is XAML work on the UI, this is a nightmare...

This is affecting WPFLocalizeExtension only as far as I can tell - our similar usage of other libraries seems to be fine in the XAML. I have tried with the original libraries we compiled on from last April, and have updated with NuGet to the latest - same problem occurs. 

I'm not a WPF/MVVM guy - I handle legacy VB6 code all day (we can't just update 2000 or so machines around the world with the latest and greatest), but luckily I teach VB.NET and C# at a major university during the evenings so the only new stuff is WPF/MVVM. Unfortunately, I was handed this project by the original dev who quit. I'm more than happy to go through the code and fix it and use the Key= notation for all my new buttons. I just would like some info on if this is a VS2015.1 issue, a WPFLocalizeExtension issue, or something from another library that I can do to prevent it. Heck, maybe the problem is in something the previous dev did and not in VS2015 at all...but any advice would be spectacular.

![problem without key](https://cloud.githubusercontent.com/assets/6171211/12687034/61569cd0-c69b-11e5-9e87-90dca5dabe69.png)

```
XAML Header is:
<UserControl Name="DVAMainScreen" 
			 xmlns:lex="http://wpflocalizeextension.codeplex.com" 
			 xmlns:ent="clr-namespace:MTI.HIW.Entities;assembly=Entities" 
			 lex:LocalizeDictionary.DesignCulture="en-US" 
			 lex:ResxLocalizationProvider.DefaultAssembly="HiwResources" 
			 lex:ResxLocalizationProvider.DefaultDictionary="TextStrings" 
			 xmlns:dva="clr-namespace:MTI.HIW.DataViewerApp" 
			 x:Class="DVAMainScreen" 
			 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
			 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" 
			 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
			 xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
			 xmlns:utilities="clr-namespace:MTI.Shared.Utilities;assembly=Utilities" 
			 mc:Ignorable="d" 
			 d:DesignHeight="1080" 
			 d:DesignWidth="1920">

Example code that causes the error:
        <Button Grid.Row="0" Grid.Column="2" Content="{lex:Loc Open}" Command="{Binding Path=OpenWeldFile}" />
```

**Comment by MrCircuit** [comment] 2016-04-24 22:04
Sorry for the late answer. I cannot reproduce the behaviour. Did you find a hint on the cause of this issue? Or can I close the Issue?

**Comment by godfetish** [comment] 2016-04-24 23:12
Seems to be ReSharper issue, but affects only this extension in this way. I
only noticed when I disabled ReSharper to debug a different problem with my
XAML references

John

Sorry for the late answer. I cannot reproduce the behaviour. Did you find a
hint on the cause of this issue? Or can I close the Issue?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/SeriousM/WPFLocalizationExtension/issues/88#issuecomment-214045894>

**Closed** 2016-04-25 17:00 UTC
