### ISSUE TITLE
No labels displayed in the designer in 3.1.0

### ISSUE THREAD

**Issue by adragoner** [SeriousM/WPFLocalizationExtension#136] opened 2018-03-20 16:39 UTC
Guys,
After recent changes (3.1.0), no labels are displayed in the designer mode.
@xmedeko, can you please have a look?

**Comment by xmedeko** [comment] 2018-03-20 20:14
Try the master branch, it works for me. I guess it's caused by the NRE when a key is null and it has been fixed in the master.

**Comment by adragoner** [comment] 2018-03-20 20:29
I'm using published nuget package in the production project.

**Comment by SeriousM** [comment] 2018-03-20 21:32
I will release a package tomorrow. Any objections about it @adragoner ?

**Comment by adragoner** [comment] 2018-03-20 21:35
I'll give it a go when published. Many thanks!

**Comment by SeriousM** [comment] 2018-03-21 15:56
Alright, new version 3.1.1 is released.

**Comment by adragoner** [comment] 2018-03-22 08:39
Guys, problem is still there.

**Comment by xmedeko** [comment] 2018-03-22 09:36
May you try the the master and the WPFLocalizationExtensionDemoApplication?

**Comment by xmedeko** [comment] 2018-03-22 20:13
Seems it's caused by #123, which has fixed the `OutputMissingKeys` behaviour.
So, in the design mode, the `LocExtension.FormatOutput` should behave like `OutputMissingKeys` is always `true`?

**Comment by xmedeko** [comment] 2018-03-25 20:44
@adragoner I've set OutputMissingKeys default to true, pls try the current master branch.

**Comment by SeriousM** [comment] 2018-03-26 04:54
Hmmm, I thought it's true by default as I wrote that... Interesting...

**Comment by adragoner** [comment] 2018-03-26 09:53
Guys, the issue is not fixed.

The expected behavior is:
- if _OutputMissingKeys_ is true then all labels with missing keys in designer should display "Key:Value", all labels with found keys should display the actual value (upon rebuild);
- if _OutputMissingKeys_ is false then all labels with missing keys in designer should be displayed blank, all labels with found keys should display the actual value (upon rebuild);
- _OutputMissingKeys_ flag should be set to true by default; <-- **Fixed by recent check-in**

**Comment by xmedeko** [comment] 2018-03-26 10:19
Yes, the demo app behave like this to me. Frankly, I do not use designer, so do not have much experience with it. Generally, I do not know which changes are reflected immediately, which upon rebuild, sometimes I need to close/open VS, ... 
Can you go back in the git commits (`git reset --hard`) to find the one which works for you as you expect? May you test both cases - the commit and master few times to make sure the problem is reproducible?

**Comment by adragoner** [comment] 2018-03-26 11:40
The designer can be quite useful for quick layout checks. The behavior I described is the desired one, but it never worked like this unfortunately - rebuild never worked properly.
As for the current issue, I downloaded latest master and labels turn blank for non-existing keys, instead of displaying "Key:Value". The latest working (except for rebuild) was 3.0.1.

**Comment by xmedeko** [comment] 2018-03-26 12:10
If it has never worked properly, then it's another story (another issue please).
Yes, this designer caching is always confusing me. So, please, just stay in the same project, switch git to 3.0.1. and them to master a few times to see if the problem is reproducible and not just a stale cache.
Or, try close VS, remove all `bin\` and  `obj\` dirs, start VS and check the master, if the "Key:Value" are back.

**Comment by adragoner** [comment] 2018-03-26 15:09
In version 3.0.1 the behavior is as follows:
- if _OutputMissingKeys_ is true then all labels with missing keys in designer are displayed as "Key:Value", all labels with found keys display the actual value. Values are not updated upon rebuild, only when VS is restarted.
- if _OutputMissingKeys_ is false then all labels with missing keys in designer **are still displayed as "Key:Value"**, all labels with found keys display the actual value. Values are not updated upon rebuild, only when VS is restarted.

In version 3.1.1 the behavior is:
- if _OutputMissingKeys_ is true then all labels with missing keys in designer **are displayed blank**, all labels with found keys display the actual value. Values are not updated upon rebuild, only when VS is restarted.
- if _OutputMissingKeys_ is false then all labels with missing keys in designer are displayed blank, all labels with found keys display the actual value. Values are not updated upon rebuild, only when VS is restarted.

So, as you can see, none of the versions actually behave as expected. However, version 3.0.1 is more usable as it displays the placeholder at least.

**Comment by SeriousM** [comment] 2018-03-26 15:38
Just for your info: design time support was never official supported by
Microsoft we can't guarantee that it works. Obviously it works for most of
the users but not all :(

**Closed** 2018-03-26 17:07 UTC

**Comment by xmedeko** [comment] 2018-03-26 17:10
@adragoner Got it. Seems like I had some stale cache before, apologies. The `LocalizeDictionary_outputMissingKeys` default value has to be sync with the DependencyProperty. I've amended the last commit, so can you try it now (`git fetch`, `git reset --hard origin/master`)?

**Comment by adragoner** [comment] 2018-03-27 07:45
Ok, fixed. Thanks! Can you please publish nuget package?

**Comment by SeriousM** [comment] 2018-03-27 13:52
> Can you please publish nuget package?

done! Version is now 3.1.2

**Comment by xmedeko** [comment] 2018-03-27 14:48
Thanks, should be in https://github.com/SeriousM/WPFLocalizationExtension/releases too.

**Comment by SeriousM** [comment] 2018-03-27 15:19
Nope, I just release on nuget, not on GitHub

**Comment by xmedeko** [comment] 2018-03-27 15:30
And who does GitHub releases?

**Comment by SeriousM** [comment] 2018-03-27 16:46
Ah, that's just tags. I CN add them if you like but these aren't binaries

**Comment by xmedeko** [comment] 2018-03-27 17:15
Well, I think just for the sake of consistency. I us these GitHub releases seldom, when I need to dowload an old version. One can easily "Edit" the changelog there as well.

**Comment by SeriousM** [comment] 2018-03-28 06:33
alright, done :)
