### ISSUE TITLE
EnumRun missing from the NuGet package

### ISSUE THREAD

**Issue by superware** [SeriousM/WPFLocalizationExtension#112] opened 2016-11-01 02:36 UTC
EnumRun seems to be missing (!) from the NuGet package build, is this possible?

**Comment by superware** [comment] 2016-11-30 09:01
Hi @SeriousM and @MrCircuit, any plans for a new release?

**Comment by superware** [comment] 2017-02-05 14:36
It also seems that besides EnumRun, EnumComboBox.PrependType is also missing from the NuGet release, any ideas? :|

**Comment by xmedeko** [comment] 2017-06-06 09:09
Duplicate of #114

**Closed** 2017-10-21 22:58 UTC
